name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Launch app-order.jar
        run: java -jar ./artifacts/app-mbank.jar &
      - name: Wait for server to start
        run: sleep 10s
      - name: Build with Gradle and run tests
        run: ./gradlew test --info
      - name: Build with Gradle
        run: ./gradlew test
